server:
  port: 8084

spring:
  application:
    name: HYBRID-BOOKING-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://hospital-db-do-user-14558489-0.b.db.ondigitalocean.com:25060/booking_service_db
    username: doadmin
    password: AVNS_ZsEHpELLbPwTvabmXJN
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  get-by-user-email : http://USER-SERVICE/user/api/v1/getByEmail
  get-by-user-id : http://USER-SERVICE/user/api/v1/getById


eureka:
  client:
    service-url:
      default-url: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true


jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F4528434567sdyfgawe675q689087564e678u9hytyfdtyuae7d8675546789654678ye6t73762358493267467834678267846yutuewiyetrETYWUIRRWERWER43454365Y4T4Y5ETW348


