server:
  port: 8084

spring:
  application:
    name: HYBRID-BOOKING-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hybrid_booking_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  get-by-user-email : http://USER-SERVICE/user/api/v1/getByEmail
  get-by-user-id : http://USER-SERVICE/user/api/v1/getById


eureka:
  client:
    service-url:
      default-url: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true


jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F452848


