server:
  port: 8084

spring:
  application:

    name: HYBRID_BOOKING-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/booking_service_db
    username: postgres
    password: 20229
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  get-by-user-id: http://USER-SERVICE/user/api/v1/getByid

eureka:
  client:
    service-url:
      default-url: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true


jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F452848
  access:
    expiry: 3000000
  refresh:
    expiry: 300000000

